### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jaf#1]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by bshannon** [comment]
Basic build job created:
https://jenkins.eclipse.org/jaf/job/jaf-branch-build/

**Comment by pzygielo** [comment]
Is there any chance to trigger https://jenkins.eclipse.org/jaf/job/jaf-master-build/ at least by code change?

**Comment by bshannon** [comment]
Yes, but since Jakarta Activation isn't required for Jakarta EE 8, work on it is a lower priority.
