### ISSUE TITLE
Integrate to GlassFish

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jaf#16]
- [ ] Integrate to Eclipse GlassFish
- [ ] Pass all CTS/TCK tests

#11 must be finished before starting working on this task.

**Comment by bshannon** [comment]
JAF is not integrated with GlassFish because it's part of Java SE 8.
When GlassFish supports SE 9 or later, it will need to integrate JAF.

The staged JAF release passes the JAF TCK.
