### ISSUE TITLE
Do not include jakarta.activation-api in jakarta.activation

### ISSUE THREAD

**Issue by ChristianCiach** [eclipse-ee4j/jaf#18]
This issue will probably be closed, because this would be a breaking change, but I still want to discuss it:

Currently, the artifact `com.sun.activation:jakarta.activation:jar` includes the entirety of `jakarta.activation:jakarta.activation-api`, instead of just depending on it.

This leads to the unfortunate situation that the dependency graph of our application (after updating to `jakarta.mail`) contains both `com.sun.activation:jakarta.activation:1.2.1` (new dependency of jakarta mail) and `javax.activation:javax.activation-api:1.2.0` (dependency of several other libraries). 

If `jakarta.activation` would instead depend on `jakarta.activation-api`, the build system (Gradle) could automatically upgrade the old dependencies of the other libraries to `jakarta.activation-api:1.2.1`. (Of course, Gradle needs to know that the module `jakarta.activation:jakarta.activation-api` is a replacement for `javax.activation:javax.activation-api`, but this is easily done with Gradle). But unfortunately, "activation" doesn't declare any relationship to "activation-api", so this is a messy thing to resolve manually.

Most (all?) other javax/jakarta projects do it better: For example, jaxb-runtime declares a dependency to jaxb-api instead of including it.

**Comment by bshannon** [comment]
The activation-api artifact should only be a compile time dependency; it's not intended to be used at runtime.  Any artifacts that are used at runtime should not depend on activation-api.

The javax.activation API classes depend on the com.sun.activation implementation classes, and vice versa.  There isn't the same API/implementation split that you find in some other projects.

**Comment by HansBrende** [comment]
@bshannon I'd really appreciate your input as regards this issue over in [this Eclipse EE4J JAXB-RI issue](https://github.com/eclipse-ee4j/jaxb-ri/issues/1284).

**Comment by bshannon** [comment]
As described above, Jakarta Activation can't easily be split into separate API and implementation artifacts.  Jakarta Activation was designed in the same style as most of the JDK classes where the implementation is part of the API classes and if you want a different implementation you use a different jar file that includes equivalent API definitions.

**Comment by dwhitla** [comment]
> The activation-api artifact should only be a compile time dependency; it's not intended to be used at runtime.

With maven a compile time dependency _is_ a runtime dependency.

**Comment by HansBrende** [comment]
@dwhitla with maven, a "compile time but not runtime dependency" means `provided` scope, not `compile` scope.

**Comment by dwhitla** [comment]
Yes but the problem is with transitive dependencies where the actual dependency should be the api not the impl.

**Comment by HansBrende** [comment]
@dwhitla in light of bshannon's reluctance to do the kind of refactor you're hoping for, I propose an even more basic fix: simply rename the artifact `jakarta.activation-api` to `jakarta.activation-with-classdefnotfounderrors` and then nobody will be tempted to use it. No api, no problem! Or rather, just delete it from maven central. I fail to see the point of that particular artifact.  The word "api" is really a misnomer in the first place, because **BOTH artifacts contain the implementation!** The only difference between the two is `activation-api` removed 10 small utility classes such as `LogSupport` on which the implementation depends.

**Comment by dwhitla** [comment]
No. Because the impl contains clases I can't force on my downstream dependents.
