### ISSUE TITLE
Update Scope Statement for Jakarta Beans Activation Framework Project

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jaf#19]
Update the scope statement for the project: https://projects.eclipse.org/projects/ee4j.jakartaee-platform/governance

See https://docs.google.com/spreadsheets/d/1FPLjo_DJDOQngVtdrYgaDk98d9NBG-0ODgdmOG3LOsI/edit?usp=sharing for examples.
--

**Comment by bshannon** [comment]
Proposed new scope statement:

Jakarta Activation lets you take advantage of standard services to: determine the MIME type of an arbitrary piece of data; encapsulate access to it; discover the operations available on it; and instantiate the appropriate bean to perform the operation(s).

**Comment by waynebeaton** [comment]
For consistency, I'm thinking that the specification **defines**.

>Jakarta Activation defines a set of standard services to: determine the MIME type of an arbitrary piece of data; encapsulate access to it; discover the operations available on it; and instantiate the appropriate bean to perform the operation(s).

**Comment by bshannon** [comment]
I'm fine with the update proposed by @waynebeaton.
Closing to indicate agreement of the project team, and requested by PMC.
