### ISSUE TITLE
Change project name to Jakarta Activation

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jaf#20]
Background information:
https://waynebeaton.wordpress.com/2019/04/04/renaming-java-ee-specifications-for-jakarta-ee/

Checklist:
- [ ]  GitHub
- [ ]  README file
- [ ]  CONTRIBUTING file
- [ ]  Eclipse Project under https://projects.eclipse.org/projects/ee4j

**Comment by ivargrimstad** [comment]
Leave out ...Framework?

**Comment by bshannon** [comment]
There are no "Jakarta Beans".

"Jakarta Activation" would be a good simple name.

**Comment by arjantijms** [comment]
@bshannon @ivargrimstad 

>"Jakarta Activation" would be a good simple name.

Yes, Jakarta Beans Activation comes of course from "JavaBeans Activation Framework" -> "Java Beans Activation Framework" -> "Jakarta Beans Activation Framework" -> "Jakarta Beans Activation", so I understand the logical derivation, but "Jakarta Activation" would IMHO be the better choice.

**Comment by bshannon** [comment]
Closing to indicate agreement of the project team, as requested by the PMC.
