### ISSUE TITLE
Convert "Eclipse Project for JAF" into a specification project

### ISSUE THREAD

**Issue by waynebeaton** [eclipse-ee4j/jaf#22]
In order to prepare this project to engage in specification work, we need to convert it into a specification project as defined by the Eclipse Foundation Specification Process (EFSP). As part of this work, we will change the project name per #20  and the scope per #19 .

We'll use this issue to capture the work that needs to be done as part of this effort.

- [x] Resolve #20 
- [x] Resolve #19 
- [x] Successful complete a restructuring review
- [x] Designate the project as a specification project of the Jakarta EE Working Group
- [x] Change project name to
- [x] Change project scope

 This assumes that the project team chooses to use a single repository for both the specification document and the existing API. Webmaster can create a separate spec repository if the project team prefers that.

**Comment by bshannon** [comment]
Note that the repository name would not include "jaf".
It would either be "activation-spec" or "jakarta-activation-spec".

**Comment by waynebeaton** [comment]
> Note that the repository name would not include "jaf".
> It would either be "activation-spec" or "jakarta-activation-spec".

Right. Updated. I've also added an entry to change the project id. There are other project repos; we should rename those while we're at it.

**Comment by waynebeaton** [comment]
We'll also have to rename the TCK repository. I've added it to the list.

**Comment by waynebeaton** [comment]
Per recent discussion with the Steering Committee, we are no longer required to change the names of the resources. I've adjusted the checklist accordingly.

I have implemented the changes. We're done here.

Please monitor the [PMC mailing list](https://accounts.eclipse.org/mailing-list/ee4j-pmc) for next steps.
