### ISSUE TITLE
Prepare Jakarta Activation for Jakarta EE 8 Release

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jaf#23]
### Instructions

- [ ] Update text files
- [ ] Generate "boilerplate" specification project
- [ ] Make a staging release
- [ ] Generate Stand-alone TCK test results
- [ ] Submit tests for ballot
- [ ] Release to Maven Central

See [here](https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release) for detailed instructions.

**Comment by bshannon** [comment]
Jakarta Activation is not a component of Jakarta EE 8.
