### ISSUE TITLE
What about the term JavaBeans?

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/jaf#28]
Is the term "JavaBeans" OK in this context?

**Comment by bshannon** [comment]
In which context?

"JavaBeans" is still a valid Java SE term.

"JavaBeans" is no longer used in the name of this project.

**Comment by keilw** [comment]
It is here https://github.com/eclipse-ee4j/jaf guess there should be more PRs to change it.

**Comment by bshannon** [comment]
Since this isn't included in Jakarta EE 8, fixing it has been a lower priority.
I'll get to it eventually.

**Comment by keilw** [comment]
Ok, at least for the checklist https://github.com/eclipse-ee4j/jaf/issues/20 seems prematurely closed ;-)

**Comment by bshannon** [comment]
Ok, ok, ok, I did it!
