### ISSUE TITLE
License specification is not clear

### ISSUE THREAD

**Issue by TobiX** [eclipse-ee4j/jaf#30]
**Describe the bug**

The repository mentions two different licenses: The "Eclipse Distribution License v. 1.0" and the "BSD  3-Clause" license. It is not really clear, which is applicable to the project, EDL, BSD or both.

- `pom.xml`: Both in comment, EDL in metadata
- `LICENSE.md`: BSD
- `NOTICE.md`: both
- `Source code comments`: both

**Expected behavior**

I should be able to see the correct licence in all those places. As far as I can see, the EDL has no official SPDX identifier, so if one wants to keep the SPDX-conformant headers and the license is, in fact, EDL, a new identifier should be [requested](https://spdx.org/spdx-license-list/request-new-license)

**Comment by bshannon** [comment]
They're two different names for the same license.  EDL is [here](https://www.eclipse.org/org/documents/edl-v10.html).
