### ISSUE TITLE
JDK 9 set as minimal JavaSE in OSGi env

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jaf#37]
**Describe the bug**
2.0.0-rc1 contains `Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=9.0))"` header in manifest which effectively means that under OSGi, JDK 9+ is required

**To Reproduce**
see rc1.jar/META-INF/MANIFEST.MF

**Expected behavior**
manifest header is either `Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"` or none. First option is preferred.

**Additional context**
caused by using old [felix-bundle-plugin](https://github.com/eclipse-ee4j/jaf/blob/master/pom.xml#L489); can be fixed either by updating the plugin to 4.2.1 (generates correct Require-Capability header) or by adding 
```
<_noee>true</_noee>
```
to plugin configuration (does not generate Require-Capability header at all)

**Comment by bshannon** [comment]
Thanks Lukas!  Fixed!

**Comment by bshannon** [comment]
Do you need me to publish a 2.0.0-RC2 for this, or can this wait until the 2.0.0 final release?

**Comment by lukasj** [comment]
depends on GF minimal runtime. Should it require SE 8, RC2 is needed sooner

**Comment by bshannon** [comment]
Thanks, Lukas.  I will publish 2.0.0-RC2 very soon.

**Comment by SmithJosh** [comment]
The 1.2.2 artifacts have the same problem with their manifests. Will you fix them as well?
