### ISSUE TITLE
Compatibility certification request for EE4J implementation of Jakarta Activation

### ISSUE THREAD

**Issue by bshannon** [eclipse-ee4j/jaf#40]
- [x] Organization Name ("Organization") and, if applicable, URL\
  [Eclipse Foundation](https://www.eclipse.org/)
- [x] Product Name, Version and download URL (if applicable)\
  [EE4J implementation of Jakarta Activation 2.0.0](https://github.com/eclipse-ee4j/jaf)
- [x] Specification Name, Version and download URL\
   [Jakarta Activation](https://jakarta.ee/activation/2.0)
- [x] TCK Version, digital SHA-256 fingerprint and download URL\
  [Jakarta Activation TCK 2.0.0](https://download.eclipse.org/jakartaee/activation/2.0/jakarta-activation-tck-2.0.0.zip), SHA-256: 98b7aad6d37cfa2eaa45ef7d182e56043a29b56ffd031a25e84e1dd2cb238f8f
- [x] Public URL of TCK Results Summary\
  [TCK results summary](https://eclipse-ee4j.github.io/jaf/TCK-Results.html)
- [x] Any Additional Specification Certification Requirements\
  None
- [x] Java runtime used to run the implementation\
  Oracle JDK 1.8.0_191
- [x] Summary of the information for the certification environment, operating system, cloud, ...\
  Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by edbratt** [comment]
Jakarta EE 9 requires Java SE 8. Please review and update. (SE11 is okay, but it is not a requirement for Jakarta EE 9.0.)

**Comment by lukasj** [comment]
@edbratt last run was with Java version: 1.8.0_191, vendor: Oracle Corporation, runtime: /opt/jdk1.8.0_191/jre - can you update the request appropriately, please? The SHA also change to "a5f85046bd15ac837dbf9d91698eb17aad219747be3d6531c6f7f8cac7489239" Thx!

**Comment by lukasj** [comment]
@m0mus SHA changed to 98b7aad6d37cfa2eaa45ef7d182e56043a29b56ffd031a25e84e1dd2cb238f8f, JDK is "Oracle JDK 1.8.0_191"

**Comment by m0mus** [comment]
@lukasj Done

**Comment by lukasj** [comment]
Approved.
