### ISSUE TITLE
rename javax.activation properties to jakarta.activation

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jaf#43]
As per [JakartaEE9ReleasePlanFAQ](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlanFAQ#should-javax-property-names-be-renamed-to-jakarta) properties javax.activation.addreverse should be changed to jakarta.activation.addreverse + javax.activation.debug to jakarta.activation.debug.

**Comment by lukasj** [comment]
I believe this has been done already. New properties are handled [here](https://github.com/eclipse-ee4j/jaf/blob/master/activation/src/main/java/com/sun/activation/registries/LogSupport.java#L26) and [here](https://github.com/eclipse-ee4j/jaf/blob/master/activation/src/main/java/com/sun/activation/registries/MailcapFile.java#L41). Or do you insist on completely removing handling of old 'javax' props? I don't believe handling old props for some time is going to hurt anyone...

**Comment by kwsutter** [comment]
Just noticed this Issue... There is no requirement to stop recognizing and processing the old javax properties.  I know of other impls that plan to support both javax and jakarta properties (as an aid with migrating).

**Comment by scottmarlow** [comment]
@lukasj @kwsutter I agree (supporting both javax.* + jakarta.* properties is more compatible) and will close this issue.

Should we update other SPEC API projects that only check for jakarta.* properties?
