### ISSUE TITLE
missing 2.0.0 release

### ISSUE THREAD

**Issue by decathorpe** [eclipse-ee4j/jaf#49]
It looks like with commit https://github.com/eclipse-ee4j/jaf/commit/f21458d58ed6728b55833817bc8ed7425c6e6fa7 the version was updated to 2.0.0 but no version 2.0.0 has been tagged in git, or was released on GitHub.

Other final releases of eclipse-ee4j projects (e.g. saaj-api 2.0.0) are starting to depend on changes that look like they would be part of this "missing" 2.0.0 release, namely the renamed packages / import paths (javax.activation → jakarta.activation).

Are issues still blocking the "official" 2.0.0 release, or was this an oversight?

**Comment by lukasj** [comment]
it's just that there is no official 2.0.0 release available to public yet as well as there is no other project suitable for public use depending on 2.0.0. The build there is a candidate being tested in other projects. Should a 3rd part project have dependency on 2.0.0 or any of its consumers, it is doing on it's own risk and till the availability of artifacts in mvn central and/or public announcement, things may change at any time without prior notice (even the "release" tag on GH).

**Comment by decathorpe** [comment]
Ok, thanks, good to know.

Side note: You might not be aware, but from a downstream perspective, repositories on GitHub modifying which commit a tag points to is a real PITA :)

**Comment by lukasj** [comment]
> Side note: You might not be aware, but from a downstream perspective, repositories on GitHub modifying which commit a tag points to is a real PITA :)

I agree but it is how it is.

**Comment by lukasj** [comment]
2.0.0 is on the way to central

**Comment by lukasj** [comment]
and the tag is going to be created in a while and it will point to e4c307a
