### ISSUE TITLE
Tasks to complete the 2.0.0 release

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/jaf#52]
The specification project team needs to complete the following to finalize the activation 2.0.0 relase:
 - [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [x] approve the compatibility request.
 - [x] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by lukasj** [comment]
done
