### ISSUE TITLE
NoClassDefFoundError: com/sun/activation/registries/LogSupport

### ISSUE THREAD

**Issue by dfcamara** [eclipse-ee4j/jaf#60]
com/sun/activation/registries is part of the source in GIT but is not present in the maven repository for version 2.0.0 so I'm getting the following error:

```
java.lang.NoClassDefFoundError: com/sun/activation/registries/LogSupport
	at jakarta.activation.MimetypesFileTypeMap.<init>(MimetypesFileTypeMap.java:100)
	at jakarta.activation.MimetypesFileTypeMap.<init>(MimetypesFileTypeMap.java:271)
```
Runnig in Eclipse Eclipse IDE for Enterprise Java Developers 2020-09, Java OpenJDK 11 and Apache Tomcat 9.0 with the following maven configuration:

```
<dependency>
  <groupId>jakarta.activation</groupId>
  <artifactId>jakarta.activation-api</artifactId>
  <version>2.0.0</version>
</dependency>
```
In [https://github.com/eclipse-ee4j/jaf/tree/master/activation/src/main/java/com/sun/activation/registries](https://github.com/eclipse-ee4j/jaf/tree/master/activation/src/main/java/com/sun/activation/registries) it is annotated "Move APIs to the jakarta.* package for the 2.0 release."

**Comment by oliverlietz** [comment]
@bshannon Will this be fixed or do we have to find a workaround (just adding the missing files to our test sources leads to `jakarta.activation.UnsupportedDataTypeException`, [SLING-10017](https://issues.apache.org/jira/browse/SLING-10017)).

**Comment by lukasj** [comment]
`jakarta.activation:jakarta.activation-api` contains APIs only and this artifact is useful at **compile-time only**. What you need for runtime and/or tests, is also an implementation. One option is to replace `jakarta.activation:jakarta.activation-api` with following artifact containing APIs as well as concrete implementation:

```
<dependency>
  <groupId>com.sun.activation</groupId>
  <artifactId>jakarta.activation</artifactId>
  <version>2.0.0</version>
</dependency>
```

@oliverlietz I'm afraid that Bill is not able to answer your question, see ie [InfoQ article](https://www.infoq.com/news/2020/07/remembering-bill-shannon/)

**Comment by Leslie-DD** [comment]
> `jakarta.activation:jakarta.activation-api` contains APIs only and this artifact is useful at **compile-time only**. What you need for runtime and/or tests, is also an implementation. One option is to replace `jakarta.activation:jakarta.activation-api` with following artifact containing APIs as well as concrete implementation:
> 
> ```
> <dependency>
>   <groupId>com.sun.activation</groupId>
>   <artifactId>jakarta.activation</artifactId>
>   <version>2.0.0</version>
> </dependency>
> ```
> 
> @oliverlietz I'm afraid that Bill is not able to answer your question, see ie [InfoQ article](https://www.infoq.com/news/2020/07/remembering-bill-shannon/)

no words to express my thx
