### ISSUE TITLE
Release 2.0.1 

### ISSUE THREAD

**Issue by tobiasKaminsky** [eclipse-ee4j/jaf#62]
2.0.0 misses some fixes: https://github.com/eclipse-ee4j/jaf/compare/2.0.0...master

In case of Android it leads to failing builds:

```
   > Failed to transform jakarta.activation-2.0.0.jar (com.sun.activation:jakarta.activation:2.0.0) to match attributes {artifactType=processed-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /home/tobi/.gradle/caches/modules-2/files-2.1/com.sun.activation/jakarta.activation/2.0.0/f4e7519148dee347c7666f336210deedb8aca09d/jakarta.activation-2.0.0.jar.
         > Failed to transform '/home/tobi/.gradle/caches/modules-2/files-2.1/com.sun.activation/jakarta.activation/2.0.0/f4e7519148dee347c7666f336210deedb8aca09d/jakarta.activation-2.0.0.jar' using Jetifier. Reason: JDOMParseException, message: Error on line 76: Präfix "Xlint" für Element "Xlint:all" ist nicht gebunden.. (Run with --stacktrace for more details.)
```

It would be great if you can release 2.0.1 with this minor bug fix 💛

**Comment by lukasj** [comment]
well, TBH if Gradle is not able to handle what is [allowed by Maven](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#compilerArguments), then it looks to me like a bug in (or an enhancement for) Gradle.

....but yes, it is better to fix it also on this project's side, 2.0.1 will go out in Q1 21

**Comment by lukasj** [comment]
waits on the approval/merge of https://github.com/jakartaee/specifications/pull/336

**Comment by lukasj** [comment]
2.0.1 is in mvn central
