### ISSUE TITLE
Move implementation out from the API repository

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jaf#73]
To make sure that APIs are really independent, implementation needs to be moved to its own repository.

Suggested new names for the implementation (feel free to suggest other names):

* Eclipse Activation
* BS-Act
* ActBS
* ???

I intend to create new project proposal for the implementation during the first week of June 2021.

**Comment by jbescos** [comment]
`Eclipse Activation` sounds good to me because the first time I hear it I associate it with Activation.

**Comment by lukasj** [comment]
Counter proposal from @edbratt is to cover activation and mail implementations in one project having two repositories.

**Comment by lukasj** [comment]
project creation review: https://projects.eclipse.org/reviews/eclipse-angus-creation-review
