### ISSUE TITLE
Final steps for Jakarta Activation 2.1

### ISSUE THREAD

**Issue by jeanouii** [eclipse-ee4j/jaf#89]
The specification project team needs to complete the following to finalize the Jakarta Activation 2.1 release:

- [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
- [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
- [x] approve the compatibility request.
- [x] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
- [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by lukasj** [comment]
you're required to move the TCK to the right location before filing this issue

**Comment by lukasj** [comment]
thanks @ivargrimstad for finding and fixing the problem
